"""empty message

Revision ID: 9c8b2ed8686b
Revises: 
Create Date: 2018-12-04 23:42:52.575084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c8b2ed8686b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluno',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('senha', sa.String(length=30), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('data_nasc', sa.Date(), nullable=False),
    sa.Column('curso', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('atividade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('prazo_entrega', sa.DateTime(), nullable=False),
    sa.Column('tag', sa.String(length=20), nullable=True),
    sa.Column('nome_disciplina', sa.String(), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('nivel_importancia', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['id_aluno'], ['aluno.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disciplina',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_aluno'], ['aluno.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('disciplina', sa.String(), nullable=False),
    sa.Column('professor', sa.String(), nullable=False),
    sa.Column('dia', sa.String(length=15), nullable=False),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('sala', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_aluno'], ['aluno.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('horario')
    op.drop_table('disciplina')
    op.drop_table('atividade')
    op.drop_table('aluno')
    # ### end Alembic commands ###
